[package]
name = "Hash_Dump"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["winreg", "winbase", "commdlg"] }
winreg = "0.10.1"
regex = "1.5.4"
aes = "0.7.5"
block-modes = "0.8.1"
des = "0.0.2"
md-5 = "0.10.1"